### PR TITLE
i3: Reformat SQL and fix collision with intarray #25

### LINKED ISSUE #25: i3 fails when intarray is installed
```
test=# create extension intarray
test-# ;
CREATE EXTENSION
test=# :dba
Menu:
   0 – Node & Current DB Information: master/replica, lag, DB size, tmp files, etc
   1 – Databases: Size, Statistics
   2 – Table Sizes
   3 – Load Profile
  a1 – Current Activity: count of current connections grouped by database, user name, state
  b1 – Tables Bloat, rough estimation
  b2 – B-tree Indexes Bloat, rough estimation
  b3 – Tables Bloat, more precise (requires pgstattuple extension; expensive)
  b4 – B-tree Indexes Bloat, more precise (requires pgstattuple extension; expensive)
  b5 – Tables and Columns Without Stats (so bloat cannot be estimated)
  i1 – Unused/Rarely Used Indexes
  i2 – Unused/Redundant Indexes Do & Undo Migration DDL
  i3 – FKs with Missing/Bad Indexes
  p1 – [EXPERIMENTAL] Alignment Padding. How many bytes can be saved if columns are ordered better?
  s1 – Slowest Queries, by Total Time (requires pg_stat_statements extension)
  s2 – Slowest Queries Report (requires pg_stat_statements)
  t1 – Postgres parameters tuning
  v1 – Vacuum: Current Activity
   x – Turn Wide Mode ON (currently OFF): show more details, more columns
   q – Quit

Type your choice and press <Enter>:
i3
psql:/home/nikolay/postgres_dba/sql/i3_non_indexed_fks.sql:125: ERROR:  operator is not unique: smallint[] @> smallint[]
LINE 60: ...(indkey::int2[])[0:(array_length(key_cols,1) -1)] @> key_col...
                                                              ^
HINT:  Could not choose a best candidate operator. You might need to add explicit type casts.
Press <Enter> to continue…
```

### PR DESCRIPTION
**Pull request by NikolayS**
- SQL fully reformatted
- the problem mentioned in #25 is fixed (here: https://github.com/NikolayS/postgres_dba/pull/35/files#diff-aefe09916bff060cdfec8903a10af1fbR66)

### CODE REVIEW

File: sql/i3_non_indexed_fks.sql [hunk 1]
```diff
@@ -6,121 +6,119 @@
...
+    indexdef,
+    array_length(key_cols, 1) as fk_colcount,
+    array_length(indkey,1) as index_colcount,
+    round(pg_relation_size(conrelid)/(1024^2)::numeric) as table_mb,
+    cols_list
+  from fk_list
+  join fk_cols_list using (fkoid)
+  left join index_list on
+    conrelid = indrelid
+    and (indkey::int2[])[0:(array_length(key_cols,1) -1)] operator(pg_catalog.@>) key_cols
```
Comment (NikolayS) [inline sql/i3_non_indexed_fks.sql]: the fix is here
